@startuml
autonumber
actor "Collaborator" as COL

activate COL
COL -> ":System" : ask to create an transaction
activate ":System"
":System" --> COL : requests various information from the transaction \n (end date, delay, brief description of the quality of the work, the task and the freelancer)
deactivate ":System"

COL -> ":System" : fill the data requested.
activate ":System"
":System" --> COL : validates the data filled, show to collaborator the amount to be paid to the freelancer \n and ask to collaborator confirm the data
deactivate ":System"

COL -> ":System" : confirm the data
activate ":System"
":System" --> COL : register the transaction and inform the collaborator the success of the operation
deactivate ":System"

deactivate COL
@enduml